# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 18:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('feed', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(3)])),
                ('rating', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('issue', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(3)])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
