# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmp4',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadmp4',
            name='code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
