# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logical', '0002_auto_20171230_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('v_id', models.CharField(max_length=250)),
                ('d_audio', models.IntegerField()),
            ],
        ),
    ]
